# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 775)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(130)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.new_button = QtWidgets.QPushButton(self.centralWidget)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout.addWidget(self.new_button)
        self.delete_button = QtWidgets.QPushButton(self.centralWidget)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.first_name_label = QtWidgets.QLabel(self.centralWidget)
        self.first_name_label.setObjectName("first_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.first_name_label)
        self.first_name_lineedit = QtWidgets.QLineEdit(self.centralWidget)
        self.first_name_lineedit.setObjectName("first_name_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.first_name_lineedit)
        self.last_name_label = QtWidgets.QLabel(self.centralWidget)
        self.last_name_label.setObjectName("last_name_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.last_name_label)
        self.last_name_lineedit = QtWidgets.QLineEdit(self.centralWidget)
        self.last_name_lineedit.setObjectName("last_name_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.last_name_lineedit)
        self.email_label = QtWidgets.QLabel(self.centralWidget)
        self.email_label.setObjectName("email_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.email_label)
        self.email_lineedit = QtWidgets.QLineEdit(self.centralWidget)
        self.email_lineedit.setObjectName("email_lineedit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.email_lineedit)
        self.username_label = QtWidgets.QLabel(self.centralWidget)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_lineedit = QtWidgets.QLineEdit(self.centralWidget)
        self.username_lineedit.setObjectName("username_lineedit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.username_lineedit)
        self.password_label = QtWidgets.QLabel(self.centralWidget)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_edit = QtWidgets.QLineEdit(self.centralWidget)
        self.password_edit.setObjectName("password_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.password_edit)
        self.confirm_label = QtWidgets.QLabel(self.centralWidget)
        self.confirm_label.setObjectName("confirm_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.confirm_label)
        self.confirm_lineedit = QtWidgets.QLineEdit(self.centralWidget)
        self.confirm_lineedit.setObjectName("confirm_lineedit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.confirm_lineedit)
        self.department_label = QtWidgets.QLabel(self.centralWidget)
        self.department_label.setObjectName("department_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.department_label)
        self.department_combo = QtWidgets.QComboBox(self.centralWidget)
        self.department_combo.setObjectName("department_combo")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.department_combo)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.update_user_button = QtWidgets.QPushButton(self.centralWidget)
        self.update_user_button.setObjectName("update_user_button")
        self.horizontalLayout_2.addWidget(self.update_user_button)
        self.cancel_button = QtWidgets.QPushButton(self.centralWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rolelist = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rolelist.sizePolicy().hasHeightForWidth())
        self.rolelist.setSizePolicy(sizePolicy)
        self.rolelist.setMinimumSize(QtCore.QSize(0, 0))
        self.rolelist.setObjectName("rolelist")
        self.verticalLayout_3.addWidget(self.rolelist)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rolecombo = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rolecombo.sizePolicy().hasHeightForWidth())
        self.rolecombo.setSizePolicy(sizePolicy)
        self.rolecombo.setObjectName("rolecombo")
        self.horizontalLayout_4.addWidget(self.rolecombo)
        self.add_button = QtWidgets.QPushButton(self.centralWidget)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_4.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.centralWidget)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout_4.addWidget(self.remove_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionsaveas = QtWidgets.QAction(MainWindow)
        self.actionsaveas.setObjectName("actionsaveas")
        self.actionrecent = QtWidgets.QAction(MainWindow)
        self.actionrecent.setObjectName("actionrecent")
        self.actionlanguage = QtWidgets.QAction(MainWindow)
        self.actionlanguage.setObjectName("actionlanguage")
        self.actionjournal = QtWidgets.QAction(MainWindow)
        self.actionjournal.setObjectName("actionjournal")
        self.actionpassword = QtWidgets.QAction(MainWindow)
        self.actionpassword.setObjectName("actionpassword")
        self.actionpasswordreset = QtWidgets.QAction(MainWindow)
        self.actionpasswordreset.setObjectName("actionpasswordreset")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionrunPerpetualy = QtWidgets.QAction(MainWindow)
        self.actionrunPerpetualy.setObjectName("actionrunPerpetualy")
        self.actionShare = QtWidgets.QAction(MainWindow)
        self.actionShare.setObjectName("actionShare")
        self.actionAddTask = QtWidgets.QAction(MainWindow)
        self.actionAddTask.setObjectName("actionAddTask")
        self.actionUnLock = QtWidgets.QAction(MainWindow)
        self.actionUnLock.setObjectName("actionUnLock")
        self.actionPage = QtWidgets.QAction(MainWindow)
        self.actionPage.setObjectName("actionPage")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Department"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Password"))
        self.new_button.setText(_translate("MainWindow", "New"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.first_name_label.setText(_translate("MainWindow", "First Name"))
        self.last_name_label.setText(_translate("MainWindow", "Last Name"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.confirm_label.setText(_translate("MainWindow", "Confirm"))
        self.department_label.setText(_translate("MainWindow", "Department"))
        self.update_user_button.setText(_translate("MainWindow", "Update User"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.remove_button.setText(_translate("MainWindow", "Remove"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsaveas.setText(_translate("MainWindow", "save as"))
        self.actionrecent.setText(_translate("MainWindow", "recent"))
        self.actionlanguage.setText(_translate("MainWindow", "language"))
        self.actionjournal.setText(_translate("MainWindow", "journal"))
        self.actionpassword.setText(_translate("MainWindow", "password"))
        self.actionpasswordreset.setText(_translate("MainWindow", "reset"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionhelp.setText(_translate("MainWindow", "help F1"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setToolTip(_translate("MainWindow", "Run"))
        self.actionrunPerpetualy.setText(_translate("MainWindow", "RunPerpetualy"))
        self.actionrunPerpetualy.setIconText(_translate("MainWindow", "RunPerpetualy"))
        self.actionrunPerpetualy.setToolTip(_translate("MainWindow", "RunPerpetualy"))
        self.actionShare.setText(_translate("MainWindow", "Share"))
        self.actionShare.setToolTip(_translate("MainWindow", "Share"))
        self.actionAddTask.setText(_translate("MainWindow", "AddTask"))
        self.actionAddTask.setToolTip(_translate("MainWindow", "AddTask"))
        self.actionUnLock.setText(_translate("MainWindow", "UnLock"))
        self.actionUnLock.setToolTip(_translate("MainWindow", "UnLock"))
        self.actionPage.setText(_translate("MainWindow", "Page"))
        self.actionPage.setToolTip(_translate("MainWindow", "Page"))

